export const quizData = {
	round1: [
		{
			id: 1,
			question: "The founder and original cartoonist of the \"Believe It or Not!\" franchise was named Robert Ripley.",
			options: ["True", "False"],
			correctAnswer: "True",
			description: "Robert LeRoy Ripley created the first \"Believe It or Not!\" cartoon panel on December 19, 1918.",
		},
		{
			id: 2,
			question: "Ripley's Believe It or Not! museums, showcasing bizarre collections, are officially called \"Odditoriums.\"",
			options: ["True", "False"],
			correctAnswer: "True",
			description: "The term \"Odditorium\" was coined during the 1933 Chicago World's Fair where Ripley opened his first major exhibition.",
		},
		{
			id: 3,
			question: "The very first \"Believe It or Not!\" cartoon panel focused entirely on unusual sports achievements.",
			options: ["True", "False"],
			correctAnswer: "True",
			description: "On December 19, 1918, Ripley compiled a list of sports records and drew them as a cartoon for the New York Globe when he was short on sports cartoon ideas.",
		},
		{
			id: 4,
			question: "Authentic shrunken heads are a signature part of the artifact collection displayed in Ripley's museums.",
			options: ["True", "False"],
			correctAnswer: "True",
			description: "Ceremonial shrunken heads (tsantsas) from the Amazon were among the very first items Robert Ripley began collecting during his travels.",
		},
		{
			id: 5,
			question: "The first \"Believe It or Not!\" cartoon strip was created and first published in the 21st century.",
			options: ["True", "False"],
			correctAnswer: "False",
			description: "The cartoon strip debuted in the early 20th century, specifically on December 19, 1918.",
		},
		{
			id: 6,
			question: "Ripley's museums frequently feature life-sized wax figure replicas of Robert Wadlow, the tallest recorded human in history.",
			options: ["True", "False"],
			correctAnswer: "True",
			description: "Robert Wadlow stood at 8 feet 11.1 inches tall. Wax figures matching his exact dimensions are iconic exhibits across many Ripley's locations.",
		},
		{
			id: 7,
			question: "Ripley's Believe It or Not! has never been adapted into a television series.",
			options: ["True", "False"],
			correctAnswer: "False",
			description: "The franchise was successfully adapted into several television series, notably hosted by Jack Palance in the 1980s and Dean Cain in the early 2000s.",
		},
		{
			id: 8,
			question: "The first permanent Ripley's Believe It or Not! Odditorium was opened in California.",
			options: ["True", "False"],
			correctAnswer: "False",
			description: "The first permanent Odditorium opened in December 1950 in St. Augustine, Florida, inside the historic Castle Warden.",
		},
		{
			id: 9,
			question: "Charles Schulz, the creator of the \"Peanuts\" comic strip, had his first cartoon published in Ripley's Believe It or Not!",
			options: ["True", "False"],
			correctAnswer: "True",
			description: "In 1937, a 15-year-old Schulz sent in a drawing of his dog, Spike, who ate pins, tacks, and razor blades. Ripley published it, marking Schulz's first professional publication.",
		},
		{
			id: 10,
			question: "The official, trademarked motto of the franchise is \"See It to Believe It.\"",
			options: ["True", "False"],
			correctAnswer: "False",
			description: "The official motto and name of the franchise is \"Believe It or Not!\".",
		},
	],
	round2: [
		{
			id: 11,
			question: "The original name of Robert Ripley's sports cartoon strip before he renamed it to \"Believe It or Not!\" was \"Champs and Chumps.\"",
			options: ["True", "False"],
			correctAnswer: "True",
			description: "When first published on December 19, 1918, in the New York Globe, the cartoon was originally titled \"Champs and Chumps\" and featured various unusual athletic feats.",
		},
		{
			id: 12,
			question: "Despite traveling to over 200 countries to find oddities, Robert Ripley had a lifelong fear of flying and preferred to travel by ship or train.",
			options: ["True", "False"],
			correctAnswer: "True",
			description: "Ripley was notoriously fearful of flying and almost always traveled by land or sea, only taking flights later in life when absolutely necessary.",
		},
		{
			id: 13,
			question: "Before his cartooning success, Robert Ripley aspired to be a professional baseball player, but his dream was ended by a broken arm.",
			options: ["True", "False"],
			correctAnswer: "True",
			description: "Ripley played semi-pro baseball and tried out for the New York Giants, but a fractured arm sustained during the tryout forced him to focus fully on illustration.",
		},
		{
			id: 14,
			question: "The researcher who verified facts for Ripley for over 50 years, Norbert Pearlroth, spoke only English.",
			options: ["True", "False"],
			correctAnswer: "False",
			description: "Norbert Pearlroth was a multilingual researcher who spoke 14 languages, allowing him to scour foreign books and archives at the New York Public Library for oddities.",
		},
		{
			id: 15,
			question: "Robert Ripley drew a cartoon pointing out that the United States did not have an official national anthem, which helped lead to \"The Star-Spangled Banner\" being officially designated in 1931.",
			options: ["True", "False"],
			correctAnswer: "True",
			description: "In his November 3, 1929 cartoon, Ripley wrote \"Believe It or Not, America has no national anthem.\" This caused massive public petitioning, leading Congress to designate \"The Star-Spangled Banner\" as the official anthem in 1931.",
		},
		{
			id: 16,
			question: "Robert Ripley passed away during the live broadcast of his own television show.",
			options: ["True", "False"],
			correctAnswer: "False",
			description: "Ripley suffered a heart attack during the filming of the 13th episode of his NBC television series on May 24, 1949, was taken to the hospital, and died three days later on May 27, 1949.",
		},
		{
			id: 17,
			question: "The very first public exhibition of Robert Ripley's collection, dubbed the \"Odditorium,\" was opened at the 1933 World's Fair in Chicago.",
			options: ["True", "False"],
			correctAnswer: "True",
			description: "The temporary exhibition was extremely popular, drawing over two million visitors during the run of the fair.",
		},
		{
			id: 18,
			question: "Ripley's Believe It or Not! is famous for owning the world's largest collection of 19th-century vampire killing kits.",
			options: ["True", "False"],
			correctAnswer: "True",
			description: "The company has acquired over 30 authentic and historically fabricated vampire killing kits from the 19th century, which are displayed in various Odditoriums.",
		},
		{
			id: 19,
			question: "Ripley's Believe It or Not! purchased Marilyn Monroe's iconic \"Happy Birthday, Mr. President\" dress at auction for $4.8 million.",
			options: ["True", "False"],
			correctAnswer: "True",
			description: "Ripley's bought the dress on November 18, 2016, setting a world record at the time for the most expensive dress ever sold at auction.",
		},
		{
			id: 20,
			question: "In 2025, Ripley's Believe It or Not! purchased the famous 18-karat solid gold toilet sculpture named \"America\" at auction for over $12 million.",
			options: ["True", "False"],
			correctAnswer: "True",
			description: "Ripley's purchased Maurizio Cattelan's fully functional solid gold toilet sculpture named \"America\" for $12.1 million at a Sotheby's auction in November 2025.",
		},
	],
	round3: [
		{
			id: 21,
			question: "Castle Warden, the home of the first permanent Ripley's museum, was originally built in 1887 as a winter residence for William G. Warden, a partner in the Standard Oil Company.",
			options: ["True", "False"],
			correctAnswer: "True",
			description: "William G. Warden was a prominent Standard Oil partner of John D. Rockefeller and Henry Flagler. The Moorish Revival-style mansion was built as his private winter estate.",
		},
		{
			id: 22,
			question: "Robert Ripley purchased Castle Warden himself to establish his museum shortly before his death.",
			options: ["True", "False"],
			correctAnswer: "False",
			description: "Although Ripley had visited and admired the building, it was his estate that purchased Castle Warden in 1950, after his death in 1949.",
		},
		{
			id: 23,
			question: "Robert Ripley once hosted a live radio broadcast from underwater while wearing a diving suit and feeding sharks.",
			options: ["True", "False"],
			correctAnswer: "True",
			description: "On February 23, 1940, Ripley hosted his radio show from inside a diving suit underwater at Marineland in St. Augustine, Florida.",
		},
		{
			id: 24,
			question: "Robert Ripley owned a private island in New York named BION Island, which was named as an acronym for \"Believe It Or Not.\"",
			options: ["True", "False"],
			correctAnswer: "True",
			description: "Ripley purchased the island in Mamaroneck, New York, in 1934, naming it \"BION Island\" (Believe It Or Not). It housed his massive personal collection of oddities.",
		},
		{
			id: 25,
			question: "Ripley's Believe It or Not! purchased the actual prop box of chocolates from the 1994 film Forrest Gump at auction.",
			options: ["True", "False"],
			correctAnswer: "True",
			description: "Ripley's purchased the iconic prop box of chocolates used by Tom Hanks in the movie at auction for $25,000.",
		},
		{
			id: 26,
			question: "The U.S. Postmaster General once officially announced that the Postal Service would no longer attempt to decode bizarrely addressed mail sent to Robert Ripley.",
			options: ["True", "False"],
			correctAnswer: "True",
			description: "In 1930, Postmaster General Walter Brown announced the post office would no longer waste time trying to decipher uniquely addressed letters (e.g., addressed in code, Braille, or drawn rebuses) sent by fans to Ripley.",
		},
		{
			id: 27,
			question: "Shortly after the fall of the Berlin Wall in 1989, Ripley's Believe It or Not! purchased a 160-foot section of the wall to display in its museums.",
			options: ["True", "False"],
			correctAnswer: "True",
			description: "Ripley's acquired sixteen 10-foot graffitied segments (totaling 160 feet) of the Berlin Wall, which are now distributed across several Odditoriums.",
		},
		{
			id: 28,
			question: "A Manchurian man named Wang, known as the \"Human Unicorn,\" was featured in early Ripley's archives for having a 13-inch horn-like growth on the back of his head.",
			options: ["True", "False"],
			correctAnswer: "True",
			description: "In 1930, a photograph of Wang showing a massive cutaneous horn protruding from the back of his head was sent to Ripley, who featured him in his cartoons.",
		},
		{
			id: 29,
			question: "Ripley's Believe It or Not! purchased an original Luke Skywalker lightsaber prop used by Mark Hamill in the original Star Wars films for $450,000.",
			options: ["True", "False"],
			correctAnswer: "True",
			description: "Ripley's purchased the original screen-used lightsaber prop, originally from the collection of producer Gary Kurtz, for $450,000 at auction in June 2017.",
		},
		{
			id: 30,
			question: "Robert Ripley was born with the first name \"Robert\" but legally changed it to \"LeRoy\" during his sports career.",
			options: ["True", "False"],
			correctAnswer: "False",
			description: "He was born LeRoy Robert Ripley, but he dropped \"LeRoy\" and went by Robert early in his career because he thought LeRoy sounded less professional.",
		},
	],
};
