export const quizData = {
	round1: [
		{
			id: 1,
			question: "The popsicle was accidentally invented by an 11-year-old child who left a cup of soda and water with a stirring stick outside on a cold night.",
			options: ["True", "False"],
			correctAnswer: "True",
			description: "Frank Epperson accidentally invented the popsicle in 1905 when he left a cup of soda powder, water, and a stirring stick on his porch overnight. It froze during a cold night, creating the first popsicle.",
		},
		{
			id: 2,
			question: "White chocolate contains cocoa solids, making it a true chocolate.",
			options: ["True", "False"],
			correctAnswer: "False",
			description: "White chocolate is not technically chocolate because it does not contain cocoa solids. Instead, it is made of cocoa butter, sugar, milk solids, and vanilla.",
		},
		{
			id: 3,
			question: "French fries were originally invented in France.",
			options: ["True", "False"],
			correctAnswer: "False",
			description: "French fries originated in Belgium, not France. Late-17th-century Belgian villagers traditionally fried small fish caught in the river, and when the river froze in winter, they cut and fried potatoes instead.",
		},
		{
			id: 4,
			question: "Cotton candy was co-invented by a dentist.",
			options: ["True", "False"],
			correctAnswer: "True",
			description: "Cotton candy was co-invented in 1897 by William Morrison, a dentist, and John C. Wharton, a confectioner. They introduced it as \"Fairy Floss\" at the 1904 St. Louis World's Fair.",
		},
		{
			id: 5,
			question: "Twinkies have a shelf life of over 10 years due to their chemical preservatives.",
			options: ["True", "False"],
			correctAnswer: "False",
			description: "Despite the popular urban legend, Twinkies actually have an official shelf life of only about 25 to 45 days.",
		},
		{
			id: 6,
			question: "The letter \"M\" printed on every M&M's candy stands for \"Melts in Mouth,\" referencing the company's famous slogan.",
			options: ["True", "False"],
			correctAnswer: "False",
			description: "The \"M\" stands for \"Mars and Murrie,\" representing Forrest Mars Sr. and Bruce Murrie, the two founders who created the candy in 1941.",
		},
		{
			id: 7,
			question: "Fortune cookies are a traditional snack that originated in China.",
			options: ["True", "False"],
			correctAnswer: "False",
			description: "Fortune cookies did not originate in China. They were created in California in the early 20th century, inspired by Japanese crackers, and popularized by Chinese-American restaurants.",
		},
		{
			id: 8,
			question: "Coca-Cola originally contained a small amount of cocaine as one of its ingredients.",
			options: ["True", "False"],
			correctAnswer: "True",
			description: "Coca-Cola originally used coca leaves, which contained small amounts of cocaine, as an ingredient. The substance was completely phased out of the recipe by 1929.",
		},
		{
			id: 9,
			question: "In the 1830s, ketchup was sold and marketed as a medicine to treat diarrhea, indigestion, and jaundice.",
			options: ["True", "False"],
			correctAnswer: "True",
			description: "In 1834, Dr. John Cook Bennett added tomatoes to ketchup (which was previously made of fish or mushrooms) and sold it in pill form as a cure for indigestion and other ailments.",
		},
		{
			id: 10,
			question: "The chocolate chip cookie was invented by Ruth Wakefield at the Toll House Inn in Massachusetts.",
			options: ["True", "False"],
			correctAnswer: "True",
			description: "Ruth Graves Wakefield invented the chocolate chip cookie in 1938 at the Toll House Inn in Whitman, Massachusetts, when she chopped up a semi-sweet Nestlé chocolate bar and added it to cookie dough.",
		},
	],
	round2: [
		{
			id: 11,
			question: "Doritos were originally invented and sold at a restaurant inside Disneyland.",
			options: ["True", "False"],
			correctAnswer: "True",
			description: "Doritos were invented at Casa de Fritos (now Rancho del Zocalo Restaurante) in Disneyland in the early 1960s. The restaurant fried up leftover tortillas and seasoned them, which became a huge success.",
		},
		{
			id: 12,
			question: "Under US FDA regulations, Pringles cannot be labeled simply as \"potato chips\" and are instead classified and sold as \"potato crisps\" because they are made from dehydrated potato flakes.",
			options: ["True", "False"],
			correctAnswer: "True",
			description: "Because Pringles are made from dehydrated potato flakes pressed into shape rather than sliced raw potatoes, the US FDA ruled in 1975 that they must be labeled as \"potato crisps\" rather than \"potato chips.\"",
		},
		{
			id: 13,
			question: "White Castle, the world's oldest fast-food hamburger chain, was founded in 1955.",
			options: ["True", "False"],
			correctAnswer: "False",
			description: "White Castle was founded in 1921. The year 1955 was when Ray Kroc opened his first franchised McDonald's restaurant in Des Plaines, Illinois.",
		},
		{
			id: 14,
			question: "Ben & Jerry's ice cream chunks are large because co-founder Ben Cohen has anosmia (no sense of smell) and relies on texture to enjoy food.",
			options: ["True", "False"],
			correctAnswer: "True",
			description: "Co-founder Ben Cohen has anosmia, meaning he has no sense of smell and a limited sense of taste. He designed the ice cream with large chunks to prioritize texture and mouthfeel.",
		},
		{
			id: 15,
			question: "Nachos were originally invented in Eagle Pass, Texas, by an American chef named Ignacio Anaya.",
			options: ["True", "False"],
			correctAnswer: "False",
			description: "Nachos were actually invented in the border city of Piedras Negras, Coahuila, Mexico, in 1943. Ignacio \"Nacho\" Anaya, a Mexican maître d', created the snack using fried tortillas, cheese, and jalapeños.",
		},
		{
			id: 16,
			question: "Graham crackers were originally designed by Sylvester Graham to be a sweet, honey-flavored dessert for children.",
			options: ["True", "False"],
			correctAnswer: "False",
			description: "Graham crackers were originally designed to be extremely bland and unsweetened. Sylvester Graham, a Presbyterian minister, introduced them in the 1830s as part of a strict vegetarian diet meant to suppress physical desires.",
		},
		{
			id: 17,
			question: "The shape of the classic Coca-Cola glass contour bottle was inspired by the shape of a cocoa pod, which designers found in an encyclopedia while researching the drink's ingredients.",
			options: ["True", "False"],
			correctAnswer: "True",
			description: "In 1915, designers at the Root Glass Company researched the ingredients of Coca-Cola in an encyclopedia to find design inspiration. They mistakenly looked up the cocoa pod (cacao tree) instead of the coca leaf, and used its ribbed, bulbous shape to design the iconic bottle.",
		},
		{
			id: 18,
			question: "The chocolate river in the 1971 film 'Willy Wonka & the Chocolate Factory' was made of real milk chocolate that was kept warm by heating pipes.",
			options: ["True", "False"],
			correctAnswer: "False",
			description: "The river was actually made of water, food coloring, and ice cream powder. Under the hot lights, the mixture fermented, rotted, and produced a terrible smell.",
		},
		{
			id: 19,
			question: "To compete with the Filet-O-Fish, McDonald's founder Ray Kroc pitched his own meatless alternative called the 'Hula Burger,' which was a grilled slice of pineapple and cheese on a bun.",
			options: ["True", "False"],
			correctAnswer: "True",
			description: "In 1962, to capture Friday sales from Catholic customers, Ray Kroc wagered Cincinnati franchisee Lou Groen that his pineapple \"Hula Burger\" would outsell Groen's \"Filet-O-Fish.\" The Filet-O-Fish won by a landslide (350 to 6).",
		},
		{
			id: 20,
			question: "The gas used to inflate potato chip bags is pure oxygen, which is added to keep the chips smelling fresh.",
			options: ["True", "False"],
			correctAnswer: "False",
			description: "Potato chip bags are actually filled with nitrogen gas, not oxygen. Oxygen would cause the oils in the chips to oxidize and go stale. Nitrogen is an inert gas that keeps the chips fresh and cushions them from breaking during shipping.",
		},
	],
	round3: [
		{
			id: 21,
			question: "Fanta was originally created in Nazi Germany during World War II because the German branch of Coca-Cola could not import the necessary syrup due to a trade embargo.",
			options: ["True", "False"],
			correctAnswer: "True",
			description: "In 1940, a wartime trade embargo made it impossible for Coca-Cola's German branch to import the secret syrup. To keep plants running, manager Max Keith developed a new drink using leftovers like whey (from cheese) and apple pomace (from cider), naming it Fanta (from \"Fantasie\").",
		},
		{
			id: 22,
			question: "The first food intentionally cooked using microwave energy during the invention of the microwave oven was a hot dog.",
			options: ["True", "False"],
			correctAnswer: "False",
			description: "The first food intentionally cooked in a microwave was popcorn. After noticing a chocolate bar had melted in his pocket, inventor Percy Spencer tested popcorn kernels next, which popped immediately. The second food was an egg, which exploded.",
		},
		{
			id: 23,
			question: "When cotton candy was introduced at the 1904 World's Fair under the name 'Fairy Floss,' it was sold for 25 cents per box, which was exactly half the price of admission to the fair itself.",
			options: ["True", "False"],
			correctAnswer: "True",
			description: "Dentist William Morrison and confectioner John C. Wharton introduced \"Fairy Floss\" at the 1904 St. Louis World's Fair. Selling it for 25 cents (when admission to the fair was 50 cents) did not stop them from selling over 68,000 boxes.",
		},
		{
			id: 24,
			question: "When the Oreo cookie was first introduced in 1912, it came in two flavors: the classic chocolate-cream and a lemon meringue flavor.",
			options: ["True", "False"],
			correctAnswer: "True",
			description: "Introduced on March 6, 1912, by the National Biscuit Company, the Oreo was sold in two flavors: the classic chocolate sandwich with vanilla creme, and a lemon meringue flavor with tart lemon filling. The lemon flavor was discontinued in the 1920s.",
		},
		{
			id: 25,
			question: "Pepsi was originally created in 1893 and sold under the name \"Caleb's Cola.\"",
			options: ["True", "False"],
			correctAnswer: "False",
			description: "Pepsi was originally created by pharmacist Caleb Bradham under the name \"Brad's Drink.\" He renamed it \"Pepsi-Cola\" in 1898, inspired by the word \"pepsin\" (representing digestion) and the \"kola nut.\"",
		},
		{
			id: 26,
			question: "The Milky Way candy bar was named after the Milky Way galaxy.",
			options: ["True", "False"],
			correctAnswer: "False",
			description: "The Milky Way candy bar, created by Frank C. Mars in 1923, was actually named after a popular malted milk drink (milkshake) of the era. The bar was designed to replicate the taste of a chocolate malted milk drink.",
		},
		{
			id: 27,
			question: "Bubble gum is traditionally pink because the inventor, Walter Diemer, only had pink food coloring available when he created his first successful batch of chewing gum.",
			options: ["True", "False"],
			correctAnswer: "True",
			description: "In 1928, Fleer Chewing Gum Company accountant Walter Diemer invented a new, less-sticky formula that could easily blow bubbles. The batch was a dull gray color, and since the only food dye available in the factory at the time was pink, he used it, setting the color standard for bubble gum forever.",
		},
		{
			id: 28,
			question: "The paper strip that sticks out from the foil wrapper of a Hershey's Kiss is officially called a \"flaglet.\"",
			options: ["True", "False"],
			correctAnswer: "False",
			description: "The Hershey Company officially calls the narrow strip of paper a \"plume.\" It was introduced in 1921 to distinguish genuine Hershey's Kisses from competitors' look-alike products.",
		},
		{
			id: 29,
			question: "Kit Kats are widely used as good-luck charms for students in Japan because the name sounds like a Japanese phrase meaning \"surely win.\"",
			options: ["True", "False"],
			correctAnswer: "True",
			description: "In Japan, \"Kit Kat\" is pronounced \"Kitto Katto,\" which sounds very similar to the phrase \"Kitto Katsu\" (きっと勝つ), translating to \"surely win\" or \"you will bound to win.\" This led to a cultural phenomenon where students carry or receive Kit Kats as encouraging gifts before exams.",
		},
		{
			id: 30,
			question: "The chocolate chip cookie is officially designated as the state cookie of New York.",
			options: ["True", "False"],
			correctAnswer: "False",
			description: "The chocolate chip cookie is actually the official state cookie of Massachusetts. It was designated as such on July 9, 1997, after a third-grade class from Somerset, Massachusetts, proposed the bill to honor the cookie's invention at the Toll House Inn in Whitman, Massachusetts.",
		},
	],
};
